rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.plugins.whenPluginAdded { plugin ->
        if ("com.android.build.gradle.LibraryPlugin" == plugin.class.name || "com.android.build.gradle.AppPlugin" == plugin.class.name) {
            if (project.android.namespace == null) {
                project.android.namespace = project.group ?: "com.example.${project.name.replace(':', '_')}"
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
